
name: pr_static_code_analysis

on:
  push:
  pull_request:

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  detekt:

    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with: {java-version: 1.11}
     - name: Run detekt
       run: ./gradlew detekt
     - name: Upload artifact 
       uses: actions/upload-artifact@v2
       with: 
          name: detekt_result
          path: build/detekt/detekt.html
 
